image: node:latest

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
  - test

install_dependencies:
  stage: build
  script: 
    - cd "$CI_PROJECT_DIR/CMS"
    - npm install
    - echo "Dependencies installed"
  
test_server:
  stage: test
  before_script:
    - node start
  script:
    - cd "$CI_PROJECT_DIR/CMS"
    - npm test
  after_script:
    - killall node

