image: node:latest

stages:
  - test

test_server:
  stage: test
  before_script:
    - cd "$CI_PROJECT_DIR/CMS"
    - npm install
    - echo "Dependencies installed"
    - npm start
  script:
    - npm test
  after_script:
    - kill -9 $(ps aux | grep '\snode\s' | awk '{print $2}')

