image: node:14.19.0

stages:
  - build
  - test

install_dependencies:
  stage: build
  script: 
    - cd "$CI_PROJECT_DIR/CMS"
    - npm install


      
start_app:
  stage: test
  needs:
    - install_dependencies
  script: 
    - cd "$CI_PROJECT_DIR/CMS"
    - npm start

  