image: node:latest

stages:
  - build
  - test

install_dependencies:
  stage: build
  script: 
    - cd "$CI_PROJECT_DIR/CMS"
    - npm install
    - echo "Dependencies installed"
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

test_server:
  stage: test
  needs:
    - install_dependencies
  before_script:
    - cd "$CI_PROJECT_DIR/CMS"
    - node start
  script:
    - npm test
  after_script:
    - killall node

