image: node:14.19.0

stages:
  - build
  - test

install_dependencies:
  entrypoint: ["/usr/bin/env"]
  stage: build
  script: 
    - cd CMS
    - npm install
  artifacts:
    paths:
      - CMS
  cache:
    key:
      files:
        - CMS/package-lock.json
    paths:
      - CMS/node_modules/
      
start_app:
  stage: test
  needs:
    - install_dependencies
  script: 
    - npm start

  