stages:
  - build
  - test

install_dependencies:
  stage: build
  script: 
    - CMS/npm install
  artifacts:
    paths:
      - CMS
  cache:
    key:
      files:
        - CMS/package-lock.json
    paths:
      - CMS/node_modules/

start_app:
  stage: test
  needs:
    - install_dependencies
  script: CMS/npm start
  artifacts:
    paths:
          - CMS
  